version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
       - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
  php:
    build:
      context: php
    volumes:
      - ./code:/var/www
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./storage/mysql:/var/lib/mysql
    env_file:
      - .env.mysql
  browser:
    hostname: browser
    image: selenium/standalone-chrome